name: Full stack CI&CD Pipeline
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  CI:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests with coverage
      run: |
        coverage run manage.py test accounts.test.auth_test
        coverage report

    # docker login

    - name: Docker login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # build and push backend

    - name: Build and push backend Image
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/django-backend:latest

    # build and push frontend
    - name: Build and push frontend Image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/react-frontend:latest
  
  deploye:
    needs: CI
    runs-on: ubuntu-latest
    if: github.ref.event_name=='push' && 'refs/heads/main'

    steps:
      - name: Deploye EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/django-backend:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/react-frontend:latest

            docker compose down
            docker compose up -d

    
  
